In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity 
pd.set_option("display.max_columns",None)
df=pd.read_csv("movies_metadata.csv",low_memory=False)
df.head()

adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1  False                                                NaN  65000000   
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3  False                                                NaN  16000000   
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                     [{'id': 35, 'name': 'Comedy'}]   

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en   
1                                   NaN   8844  tt0113497                en   
2                                   NaN  15602  tt0113228                en   
3                                   NaN  31357  tt0114885                en   
4                                   NaN  11862  tt0113041                en   

                original_title  \
0                    Toy Story   
1                      Jumanji   
2             Grumpier Old Men   
3            Waiting to Exhale   
4  Father of the Bride Part II   

                                            overview popularity  \
0  Led by Woody, Andy's toys live happily in his ...  21.946943   
1  When siblings Judy and Peter discover an encha...  17.015539   
2  A family wedding reignites the ancient feud be...    11.7129   
3  Cheated on, mistreated and stepped on, the wom...   3.859495   
4  Just when George Banks has recovered from his ...   8.387519   

                        poster_path  \
0  /rhIRbceoE9lR4veEXuwCC2wARtG.jpg   
1  /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg   
2  /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg   
3  /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg   
4  /e64sOI48hQXyru7naBFyssKFxVd.jpg   

                                production_companies  \
0     [{'name': 'Pixar Animation Studios', 'id': 3}]   
1  [{'name': 'TriStar Pictures', 'id': 559}, {'na...   
2  [{'name': 'Warner Bros.', 'id': 6194}, {'name'...   
3  [{'name': 'Twentieth Century Fox Film Corporat...   
4  [{'name': 'Sandollar Productions', 'id': 5842}...   

                                production_countries release_date  \
0  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-10-30   
1  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-15   
2  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22   
3  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22   
4  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-02-10   

       revenue  runtime                                   spoken_languages  \
0  373554033.0     81.0           [{'iso_639_1': 'en', 'name': 'English'}]   
1  262797249.0    104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...   
2          0.0    101.0           [{'iso_639_1': 'en', 'name': 'English'}]   
3   81452156.0    127.0           [{'iso_639_1': 'en', 'name': 'English'}]   
4   76578911.0    106.0           [{'iso_639_1': 'en', 'name': 'English'}]   

     status                                            tagline  \
0  Released                                                NaN   
1  Released          Roll the dice and unleash the excitement!   
2  Released  Still Yelling. Still Fighting. Still Ready for...   
3  Released  Friends are the people who let you be yourself...   
4  Released  Just When His World Is Back To Normal... He's ...   

                         title  video  vote_average  vote_count  
0                    Toy Story  False           7.7      5415.0  
1                      Jumanji  False           6.9      2413.0  
2             Grumpier Old Men  False           6.5        92.0  
3            Waiting to Exh

indexler sıralı değilse reset index yapmak gerekir

In [2]:
df.shape

(45466, 24)

In [3]:
df["overview"].head()

0    Led by Woody, Andy's toys live happily in his ...
1    When siblings Judy and Peter discover an encha...
2    A family wedding reignites the ancient feud be...
3    Cheated on, mistreated and stepped on, the wom...
4    Just when George Banks has recovered from his ...
Name: overview, dtype: object

In [4]:
df["overview"].isnull().sum()

954

In [5]:
df["overview"] = df["overview"].fillna("")

In [6]:
tfidf = TfidfVectorizer(stop_words="english")
tfidf_matrix = tfidf.fit_transform(df["overview"])
tfidf_matrix

<45466x75827 sparse matrix of type '<class 'numpy.float64'>'
	with 1210882 stored elements in Compressed Sparse Row format>

In [7]:
tfidf_matrix.shape

(45466, 75827)

In [8]:
tfidf.get_feature_names_out()

array(['00', '000', '000km', ..., '첫사랑', 'first', 'five'], dtype=object)

In [9]:
cosine_sim = cosine_similarity(tfidf_matrix,tfidf_matrix)
cosine_sim.shape

(45466, 45466)

In [10]:
cosine_sim[1] #bu index seçer

array([0.01504121, 1.        , 0.04681953, ..., 0.        , 0.02198641,
       0.00929411])

In [73]:
cosine_sim[:,1] # bu kolon (sütun) seçer

array([0.01504121, 1.        , 0.04681953, ..., 0.        , 0.02198641,
       0.00929411])

In [71]:
cosine_sim[1,1]

1.0000000000000002

In [11]:
indices = pd.Series(df.index, index=df["title"])
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...  
Subdue                         45461
Century of Birthing            45462
Betrayal                       45463
Satan Triumphant               45464
Queerama                       45465
Length: 45466, dtype: int64

In [12]:
indices.index.value_counts()

title
Cinderella              11
Hamlet                   9
Alice in Wonderland      9
Beauty and the Beast     8
Les Misérables           8
                        ..
Cluny Brown              1
Babies                   1
The Green Room           1
Captain Conan            1
Queerama                 1
Name: count, Length: 42277, dtype: int64

In [13]:
indices.index.duplicated(keep="last")

array([False, False, False, ..., False, False, False])

In [19]:
indices[~indices.index.duplicated(keep="last")]

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...  
Subdue                         45461
Century of Birthing            45462
Betrayal                       45463
Satan Triumphant               45464
Queerama                       45465
Length: 42278, dtype: int64

In [33]:
indices = indices[~indices.index.duplicated(keep="last")]

In [29]:
a = pd.Series([1,2,3,4,5,6],index = ["a","a","b","a","c","a"])
a

a    1
a    2
b    3
a    4
c    5
a    6
dtype: int64

In [30]:
a.index.duplicated()

array([False,  True, False,  True, False,  True])

In [65]:
a.index.duplicated(keep="last")

array([ True,  True, False,  True, False, False])

In [31]:
~a.index.duplicated(keep="last")

array([False, False,  True, False,  True,  True])

In [32]:
a[~a.index.duplicated(keep="last")]

b    3
c    5
a    6
dtype: int64

In [51]:
a["a"]

a    1
a    2
a    4
a    6
dtype: int64

In [54]:
a

a    1
a    2
b    3
a    4
c    5
a    6
dtype: int64

In [53]:
a[2]

3

In [58]:
2 in a.values

True

In [67]:
a["b"]

3

In [60]:
a[a>4]

c    5
a    6
dtype: int64

In [34]:
movie_index = indices["Sherlock Holmes"]
movie_index

35116

In [68]:
cosine_sim.shape

(45466, 45466)

In [70]:
cosine_sim[movie_index]

array([0.        , 0.00392837, 0.00476764, ..., 0.        , 0.0067919 ,
       0.        ])

In [74]:
cosine_sim[:,movie_index]

array([0.        , 0.00392837, 0.00476764, ..., 0.        , 0.0067919 ,
       0.        ])

In [46]:
smilarity_scores=pd.DataFrame(cosine_sim[movie_index],columns=["score"])
smilarity_scores

score
0      0.000000
1      0.003928
2      0.004768
3      0.000000
4      0.000000
...         ...
45461  0.000000
45462  0.000000
45463  0.000000
45464  0.006792
45465  0.000000

[45466 rows x 1 columns]

In [48]:
movie_indices=smilarity_scores.sort_values("score",ascending=False)[1:11].index
movie_indices

Index([34737, 14821, 34750, 9743, 4434, 29706, 18258, 24665, 6432, 29154], dtype='int64')

In [49]:
df["title"].iloc[movie_indices]

34737    Приключения Шерлока Холмса и доктора Ватсона: ...
14821                                    The Royal Scandal
34750    The Adventures of Sherlock Holmes and Doctor W...
9743                           The Seven-Per-Cent Solution
4434                                        Without a Clue
29706                       How Sherlock Changed the World
18258                   Sherlock Holmes: A Game of Shadows
24665     The Sign of Four: Sherlock Holmes' Greatest Case
6432                   The Private Life of Sherlock Holmes
29154                          Sherlock Holmes in New York
Name: title, dtype: object

In [78]:
cosine_sim.shape[0]

45466

In [76]:
def get_similar_movies(cosine_sim, num_similar_movies=10):
    # A dictionary to store similarity results for each movie
    similarity_dict = {}
    
    # Loop over each movie index in the cosine similarity matrix
    for movie_index in range(cosine_sim.shape[0]):
        # Create a DataFrame for similarity scores of the current movie index
        smilarity_scores = pd.DataFrame(cosine_sim[movie_index], columns=["score"])
        
        # Sort the scores in descending order and get indices of the top similar movies
        # Exclude the first index because it is the same movie
        similar_movie_indices = smilarity_scores.sort_values("score", ascending=False)[1:num_similar_movies+1].index
        
        # Add the results to the dictionary
        similarity_dict[movie_index] = similar_movie_indices.tolist()
    
    return similarity_dict

In [80]:
def get_similar_movies(cosine_sim, movie_index, num_similar_movies=10):
    # Create a dictionary to store similarity results
    similarity_dict = {}
    
    # Create a DataFrame for similarity scores of the provided movie index
    smilarity_scores = pd.DataFrame(cosine_sim[movie_index], columns=["score"])
    
    # Sort the scores in descending order and get indices of the top similar movies
    # Exclude the first index because it is the same movie
    similar_movie_indices = smilarity_scores.sort_values("score", ascending=False)[1:num_similar_movies+1].index

    # Store the indices of similar movies in the dictionary
    similarity_dict[movie_index] = similar_movie_indices.tolist()

    return similarity_dict


In [81]:
get_similar_movies(cosine_sim,movie_index)

{35116: [34737, 14821, 34750, 9743, 4434, 29706, 18258, 24665, 6432, 29154]}

In [62]:
def content_based_recommender(title,cosine_sim,df):
    #indexleri oluşturma
    indices = pd.Series(df.index,index =df["title"])
    indices = indices[~indices.index.duplicated(keep="last")]
    # title ın indexini yakalama
    movie_index = indices[title]
    # title a göre benzerlik skorlarının hesaplanması
    similarity_scores = pd.DataFrame(cosine_sim[movie_index],columns=["score"])
    # kendisi hariç ilk 10 film
    movie_indices = similarity_scores.sort_values("score",ascending=False)[1:11].index
    return df["title"].iloc[movie_indices]

In [63]:
content_based_recommender("Sherlock Holmes",cosine_sim,df)

34737    Приключения Шерлока Холмса и доктора Ватсона: ...
14821                                    The Royal Scandal
34750    The Adventures of Sherlock Holmes and Doctor W...
9743                           The Seven-Per-Cent Solution
4434                                        Without a Clue
29706                       How Sherlock Changed the World
18258                   Sherlock Holmes: A Game of Shadows
24665     The Sign of Four: Sherlock Holmes' Greatest Case
6432                   The Private Life of Sherlock Holmes
29154                          Sherlock Holmes in New York
Name: title, dtype: object

In [64]:
def calculate_cosine_sim(df):
    tfidf = TfidfVectorizer(stop_words="english")
    df["overview"] = df["overview"].fillna("")
    tfidf_matrix = tfidf.fit_transform(df["overview"])
    cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
    return cosine_sim

In [ ]:
def sim_dict(df,cosine_sim,movie_index,count=10,name=False):
    
    sim_dict = {}
    sim_df = pd.DataFrame(cosine_sim[movie_index],columns=["sim"])
    sim_list = list(sim_df.sort_values("sim",ascending=False)[1:10].index)    
    if name:
        sim_dict[df["title"].iloc[movie_index]] = list(df["title"].iloc[sim_list].values)
    else:
        sim_dict[movie_index] = list(df["title"].iloc[sim_list].index)
    
    
    return sim_dict

sim_dict(df,cosine_sim,0,count=10,name=True)